#!/usr/bin/env python3
"""Generates the in-app legal texts from docs/*.md:
  docs/privacy.md, docs/agreement.md        -> entry/src/main/ets/common/i18n/LegalZh.ets
  docs/privacy_en.md, docs/agreement_en.md  -> entry/src/main/ets/common/i18n/LegalEn.ets
Run after editing any of the docs. Do not edit the generated files by hand."""
import json, os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')


def lines(p):
    ls = open(os.path.join(root, p), encoding='utf-8').read().split('\n')
    while ls and ls[-1] == '':
        ls.pop()
    return ls


def gen(out_name, lang, docs):
    out = ['/** %s legal texts. Generated by scripts/gen-legal.py from %s; do not edit by hand. */' % (lang, ', '.join(d[1] for d in docs)), '']
    for name, p in docs:
        out.append('export const %s: string[] = [' % name)
        out.append(',\n'.join('  ' + json.dumps(l, ensure_ascii=False) for l in lines(p)))
        out.append('];')
        out.append('')
    open(os.path.join(root, 'entry/src/main/ets/common/i18n', out_name), 'w', encoding='utf-8').write('\n'.join(out))


gen('LegalZh.ets', 'Chinese', [('PRIVACY_ZH', 'docs/privacy.md'), ('AGREEMENT_ZH', 'docs/agreement.md')])
gen('LegalEn.ets', 'English', [('PRIVACY_EN', 'docs/privacy_en.md'), ('AGREEMENT_EN', 'docs/agreement_en.md')])
